### ISSUE TITLE
Flutter 3.0 运行报错

### ISSUE THREAD

**Issue by GvcZhang** [simplezhli/flutter_deer#208]
一些 Flutter 的 API 发生了变化，导致代码中和依赖的第三方库都需要做适配。

**Comment by xueqiulou** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by simplezhli** [comment]
@GvcZhang 目前发现是qr_code_scanner库的问题，可以先替换为：
```
 qr_code_scanner:
    git:
      url: https://github.com/xeinebiu/qr_code_scanner.git
      ref: fix_break_changes_platform
```

后面我会提交修复后的代码。
